// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gutgifytxvcjvajrlhwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1dGdpZnl0eHZjanZhanJsaHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDg3NzIsImV4cCI6MjA3MjEyNDc3Mn0.tp1iFevnitQFp8lE-55B8N_SxDnIoWPycs5CIpsoMFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});